server:
  port: 7777
  shutdown: graceful


spring:
  application:
    name: api-gateway
  main:
    banner-mode: off

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: lb://auth-service

              predicates:
                - Path= /api/v1/auth/**,/api/v1/users/**
              filters:
                - StripPrefix=0

            - id: scan-service-route
              uri: lb://scan-service
              predicates:
                - Path=/api/v1/scan/**
              filters:
                - StripPrefix=0

            - id: nmap-service-route
              uri: lb://nmap-service
              predicates:
                - Path=/api/v1/daemon/start
                - Method=POST
              filters:
                - StripPrefix=0

            - id: report-service-route
              uri: lb://report-service
              predicates:
                - Path=/api/v1/report/**
              filters:
                - StripPrefix=0
  lifecycle:
    timeout-per-shutdown-phase: 30s

jwt:
  secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true