server:
  port: 8085
  shutdown: graceful

spring:
  application:
    name: report-service
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

minio:
  #  endpoint: ${MINIO_ENDPOINT:http://192.168.29.50:9000}
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:sentinel}
  secret-key: ${MINIO_SECRET_KEY:sentinel123}
  bucket: ${MINIO_BUCKET:sentinel-reports}
  # Pre-signed URL expiry in minutes
  url-expiry-minutes: ${MINIO_URL_EXPIRY:60}

scan-service:
  base-url: lb://scan-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

report:
  download-base-url: ${REPORT_DOWNLOAD_BASE_URL:http://localhost:7777}