POST {{host}}/api/v1/auth/refresh
Authorization: Bearer {{refreshToken}}

> {%
    const body = response.body;

    client.global.set("accessToken", body.accessToken);
    client.global.set("refreshToken", body.refreshToken);
%}
