server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: nmap-service
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 30s

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: nmap-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.type.mapping: scanCommand:org.sentinel.nmapservice.model.ScanCommandMessage
        spring.json.trusted.packages: "org.sentinel.nmapservice.model"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
    listener:
      concurrency: 3 # number of Kafka consumer threads (partition count = 3, so 1:1)

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: scanResult:org.sentinel.nmapservice.model.ScanResultMessage
        acks: all
        retries: 3
        enable.idempotence: true

topics:
  input-name: scan_cmd
  output-name: scan_result

docker:
#  host: unix:///var/run/docker.sock
  host: tcp://localhost:2375 #For docker running on Windows

nmap:
  image: "instrumentisto/nmap:latest"
  scan-timeout-minutes: 5

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true