server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: scan-service
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    #    url: jdbc:mysql://localhost:3306/scan_results
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/scan_results}
    username: ${DB_USERNAME:sentinel}
    password: ${DB_PASSWORD:sentinel} 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.type.mapping: scanCommand:org.sentinel.scanservice.model.ScanCommandMessage
        acks: all
        retries: 3
        enable.idempotence: true

    consumer:
      group-id: scan-service-results
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.type.mapping: scanResult:org.sentinel.scanservice.model.ScanResultMessage
        spring.json.trusted.packages: "org.sentinel.scanservice.model"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        max.poll.records: 10

topics:
  output-name: scan_cmd
  input-name: scan_result

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging:
  level:
    # Your application code
    org.sentinel.scanservice: DEBUG

    # Apache HttpClient wire – shows full request/response headers, body, SSL handshake
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG

    # Spring Retry – shows when retries happen and why
    org.springframework.retry: DEBUG

    # Spring Web (RestTemplate)
    org.springframework.web.client.RestTemplate: DEBUG

    # Hibernate SQL binding (optional, for DB queries)
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
